// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBRIpOV7yz18kPjp0MIKQR3zsTRLCgfGu4',
//     appId: '1:328591552399:web:2553a437cb39b61349a5fa',
//     messagingSenderId: '328591552399',
//     projectId: 'trawell-22045',
//     authDomain: 'trawell-22045.firebaseapp.com',
//     storageBucket: 'trawell-22045.appspot.com',
//     measurementId: 'G-F6R1E37546',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCqNgHgy1AXH0Y-1gKBGcmMWXE6grwAAIg',
//     appId: '1:328591552399:android:dce44106caa4f7f549a5fa',
//     messagingSenderId: '328591552399',
//     projectId: 'trawell-22045',
//     storageBucket: 'trawell-22045.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBIDR--3FegRQWTYH8FDDjoBeekTWFL4CU',
//     appId: '1:328591552399:ios:70c4546f9a09e47549a5fa',
//     messagingSenderId: '328591552399',
//     projectId: 'trawell-22045',
//     storageBucket: 'trawell-22045.appspot.com',
//     iosClientId: '328591552399-jla5kj1ihq3o3dsuu8g9mibq7h50nm96.apps.googleusercontent.com',
//     iosBundleId: 'com.example.trawell',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBIDR--3FegRQWTYH8FDDjoBeekTWFL4CU',
//     appId: '1:328591552399:ios:70c4546f9a09e47549a5fa',
//     messagingSenderId: '328591552399',
//     projectId: 'trawell-22045',
//     storageBucket: 'trawell-22045.appspot.com',
//     iosClientId: '328591552399-jla5kj1ihq3o3dsuu8g9mibq7h50nm96.apps.googleusercontent.com',
//     iosBundleId: 'com.example.trawell',
//   );
// }
